% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function T = addSurface(T, Radius, Thickness, SurfaceType, SurfaceData, MaterialType, IndexData, AxisData, CoatingData)
%ADDSURFACE Add one surface row to a prtLab optical system table.
%
%   T = addSurface(T, Radius, Thickness, SurfaceType, SurfaceData, ...
%       MaterialType, IndexData, AxisData)
%
%   T = addSurface(..., CoatingData)
%
%   SurfaceData, IndexData, AxisData, and CoatingData are stored as cell
%   contents so they can be structs with fields appropriate to each surface.

arguments
    T table
    Radius (1,1) double
    Thickness (1,1) double
    SurfaceType (1,1) string
    SurfaceData (1,1) struct
    MaterialType (1,1) string
    IndexData (1,1) struct
    AxisData (1,1) struct
    CoatingData (1,1) struct = struct('type', 'none')
end

expectedNames = { ...
    'Radius', ...
    'Thickness', ...
    'SurfaceType', ...
    'SurfaceData', ...
    'MaterialType', ...
    'IndexData', ...
    'AxisData', ...
    'CoatingData'};

assert(all(ismember(expectedNames, T.Properties.VariableNames)), ...
    'addSurface:InvalidTable', ...
    'Input table does not look like a prtLab optical system table.');

newRow = table( ...
    Radius, ...
    Thickness, ...
    SurfaceType, ...
    {SurfaceData}, ...
    MaterialType, ...
    {IndexData}, ...
    {AxisData}, ...
    {CoatingData}, ...
    'VariableNames', expectedNames);

T = [T; newRow];

end
