% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function scene = createGlanTaylorPolarizerScene(indexData, options)
%CREATEGLANTAYLORPOLARIZERSCENE Create two crystal prisms with an air gap.
%
%   This constructor supplies geometry only. Polarization splitting and
%   TIR behavior are determined by the applicable interface trace routines.

arguments
    indexData (1,1) struct
    options.LegY (1,1) double {mustBePositive} = 10
    options.LegZ (1,1) double {mustBePositive} = 10
    options.Width (1,1) double {mustBePositive} = 8
    options.AirGap (1,1) double {mustBePositive} = 0.02
    options.Origin (3,1) double = [0;0;0]
    options.OpticAxis (3,1) double = [1;0;0]
    options.OutsideIndex (1,1) double {mustBePositive} = 1.0
    options.lambda (1,1) double {mustBePositive} = 0.633
    options.lambdaUnits (1,1) string = "um"
    options.Name (1,1) string = "Glan-Taylor polarizer"
end

scene = createPrtScene(options.lambda, options.OutsideIndex, ...
    lambdaUnits=options.lambdaUnits, Name=options.Name);

prism1 = createRightTriangularPrismSolid(indexData, ...
    LegY=options.LegY, ...
    LegZ=options.LegZ, ...
    Width=options.Width, ...
    Origin=options.Origin, ...
    OpticAxis=options.OpticAxis, ...
    OutsideIndex=options.OutsideIndex, ...
    lambda=options.lambda, ...
    lambdaUnits=options.lambdaUnits, ...
    Name="Glan-Taylor prism 1");

hypotenuseIndex = find([prism1.faces.name] == "hypotenuse", 1);
gapDirection = prism1.faces(hypotenuseIndex).normal;
prism2Origin = options.Origin + ...
    [0; options.LegY; options.LegZ] + options.AirGap*gapDirection;
prism2 = createRightTriangularPrismSolid(indexData, ...
    LegY=options.LegY, ...
    LegZ=options.LegZ, ...
    Width=options.Width, ...
    Origin=prism2Origin, ...
    YDirection=-1, ...
    ZDirection=-1, ...
    OpticAxis=options.OpticAxis, ...
    OutsideIndex=options.OutsideIndex, ...
    lambda=options.lambda, ...
    lambdaUnits=options.lambdaUnits, ...
    Name="Glan-Taylor prism 2");

scene = addSolidToPrtScene(scene, prism1);
scene = addSolidToPrtScene(scene, prism2);
scene.geometry = struct( ...
    'type', "GlanTaylor", ...
    'airGap', options.AirGap, ...
    'legY', options.LegY, ...
    'legZ', options.LegZ, ...
    'width', options.Width, ...
    'opticAxis', options.OpticAxis/norm(options.OpticAxis));

end
