function T = createOpticalSystem(lambda)
%CREATEOPTICALSYSTEM Create an empty polarization ray tracing system table.
%
%   T = createOpticalSystem(lambda) creates an empty optical system table.
%   lambda is stored in T.Properties.UserData.lambda and is assumed to use
%   the same length units as any wavelength-dependent system data.

arguments
    lambda (1,1) double {mustBePositive}
end

T = table( ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1), ...
    cell(0,1), ...
    strings(0,1), ...
    cell(0,1), ...
    cell(0,1), ...
    cell(0,1), ...
    'VariableNames', { ...
        'Radius', ...
        'Thickness', ...
        'SurfaceType', ...
        'SurfaceData', ...
        'MaterialType', ...
        'IndexData', ...
        'AxisData', ...
        'CoatingData'});

T.Properties.UserData.lambda = lambda;
T.Properties.UserData.lambdaUnits = '';
T.Properties.UserData.description = 'prtLab optical system table';

end
