function ray = emptyRayBranch()
%EMPTYRAYBRANCH Template for a ray-tree branch.

ray = struct( ...
    'id', [], ...
    'parentId', [], ...
	    'surfaceIndex', [], ...
	    'mode', "", ...
	    'branchType', "", ...
	    'mediumType', "", ...
    'position', zeros(3,1), ...
    'k', zeros(3,1), ...
    'S', zeros(3,1), ...
    'modeE', zeros(3,1), ...
    'modeH', zeros(3,1), ...
    'fieldE', zeros(3,1), ...
    'fieldH', zeros(3,1), ...
    'E', zeros(3,1), ...
    'H', zeros(3,1), ...
    'P', eye(3), ...
    'Q', eye(3), ...
    'O', eye(3), ...
    'localBasis', struct(), ...
    'amplitude', [], ...
    'flux', [], ...
    'OPL', [], ...
    'active', false, ...
    'history', [], ...
    'metadata', struct());

end
