function interaction = emptyInteractionRecord()
%EMPTYINTERACTIONRECORD Template for a surface interaction record.

interaction = struct( ...
    'surfaceIndex', [], ...
    'parentRayId', [], ...
    'caseName', "", ...
    'position', zeros(3,1), ...
    'normal', zeros(3,1), ...
    'incident', struct(), ...
    'exiting', struct([]), ...
    'frames', struct(), ...
    'children', repmat(emptyRayBranch(), 0, 1), ...
    'P', struct(), ...
    'Q', struct(), ...
    'coefficients', struct(), ...
    'diagnostics', struct(), ...
    'interceptData', struct());

end
