function interaction = traceUniaxialToIsotropic(interaction, mediumIn, mediumOut, ray, hit, normal, options)
%TRACEUNIAXIALTOISOTROPIC trace rays from uniaxial to isotropic materials
%Based on PLAOS Section 19.7.3


deg = pi/180;

k_inc = interaction.incident.k;
S_inc = interaction.incident.S;
E_inc = interaction.incident.modeE;
H_inc = interaction.incident.modeH;
iStruct = mediumIn.IndexData{1};
nO = iStruct.nO;
nE = iStruct.nE;
if strcmp(interaction.incident.mode, "ordinary")
    n_inc = iStruct.nO;
else
    n_inc = ray.metadata.n;
end
ada = interaction.normal;


Iin  = dot(cross(E_inc, conj(H_inc)), ada);
IinField = dot(cross(ray.fieldE, conj(ray.fieldH)), ada);

E_n = cross(S_inc,E_inc);
E_n = E_n/norm(E_n);

oStruct = mediumOut.IndexData{1};
n_out = oStruct.n;

tir = isTotalInternalReflection(k_inc, ada, n_inc, n_out);


% Use snell's law to calculate the exit fields.  Since this is birefringent
% to isotropic there is no issue with treating the o and e waves separately

% TODO:  Refactor this as it is common with other trace methods
k_out = snell_vector(k_inc, ada, n_inc, n_out);
S_out = k_out;
[E_tb, E_ta] = calcPandSUnitVectors(k_out, ada) ;
K_out = makeK(k_out);
H_ta = n_out*K_out * E_ta;
H_tb = n_out*K_out * E_tb;


%% Reflection 
% need to account for the possibility of two reflected waves for
% extraordinary wave.  

axisData = mediumIn.AxisData{1};
opticAxis = axisData.opticAxis;


a = opticAxis(:) / norm(opticAxis); % norm here is unnecessary since it is handled when sout.opticAxis is defined

% I need to construct a basis of 3 vectors, 2 orthogonal to a.  It doesn't
% matter which two vectors I choose; the a*a' accomplishes this.
epsilon = nO^2*eye(3) + (nE^2 - nO^2)*(a*a.');


% Compute o and e reflected waves
qInc = n_inc*k_inc;
[n_ref, k_ref_e, q_ref] = extraordinaryReflectedQ(qInc, ada, opticAxis, nO, nE);

qParallel = qInc - dot(qInc,ada)*ada;
qNormalO = -sqrt(nO^2 - dot(qParallel,qParallel));
qRefO = qParallel + qNormalO*ada;
k_ref_o = qRefO/nO;


K_re = makeK(k_ref_e);
M_re = epsilon + (n_ref*K_re)*(n_ref*K_re);
det(M_re) ;% should be close to eps
%norm((epsilon + makeK(q_ref)^2) * E_re) % should be close to eps

[Utmp,Stmp,V] = svd(M_re);
% if opticAxis, ada, and k_inc all in same direction, have a degeneracy
% that needs to be handled.
if all(opticAxis == k_inc) && all(opticAxis == ada)
   E_re = V(:,end-1);
else
   E_re = V(:,end);
end

H_re = n_ref*K_re*E_re;

K_ro = makeK(k_ref_o);
M_ro = epsilon + (nO*K_ro)*(nO*K_ro);

det(M_ro) ; % should be close to eps

[Utmp,Stmp,V] = svd(M_ro);
%
E_ro = V(:,end);
H_ro = nO*K_ro*E_ro;

S_ro = cross(E_ro,H_ro);
S_ro = S_ro/norm(S_ro);

S_re = prtNorm(cross(E_re, H_re));

%% -------------------------------------------------------
% s-basis vectors - vectors transverse to the interface
%% -------------------------------------------------------
if (k_inc(1) == 0 && k_inc(2) == 0 && k_inc(3) == 1) % special case normal incidence
    s1 = [1;0;0];
else
    s1 = cross(k_inc, ada);
    s1 = s1/norm(s1);
end
s2 = cross(ada, s1);
s2 = s2/norm(s2);


%% -------------------------------------------------------
% Construct F matrix for this interface
%% -------------------------------------------------------
F = [ ...
 dot(s1,E_ta) dot(s1,E_tb) -dot(s1,E_ro) -dot(s1,E_re);
 dot(s2,E_ta) dot(s2,E_tb) -dot(s2,E_ro) -dot(s2,E_re);
 dot(s1,H_ta) dot(s1,H_tb) -dot(s1,H_ro) -dot(s1,H_re);
 dot(s2,H_ta) dot(s2,H_tb) -dot(s2,H_ro) -dot(s2,H_re) ];


Cm = [ dot(s1,E_inc); dot(s2,E_inc); dot(s1,H_inc); dot(s2,H_inc) ];
% This is the case III condition from chapter 19
Cn = zeros(size(Cm));


Am = F\Cm; % or F\Cs
Ap = zeros(size(Am)); % or F\Cp 

% If tir condtion satisfied then force transmitted wave to nothing.
if ~tir
    P_t = [Am(1)*E_ta+Am(2)*E_tb, zeros(size(E_ta)), S_out]*inv([E_inc, E_n, S_inc]);
else
    P_t = zeros(3);
end

P_ro  = [Am(3)*E_ro, zeros(size(E_ro)), S_ro]/ ...
         ([E_inc, E_n, S_inc]);
P_re  = [Am(4)*E_re, zeros(size(E_re)), S_re]/ ...
         ([E_inc, E_n, S_inc]);


% Diagnostic TODO:  Port over from traceUniaxialtoUnixial - abstract?

if ~tir
    E_out = Am(1)*E_ta+Am(2)*E_tb;
    H_out = Am(1)*H_ta+Am(2)*H_tb;
else
    E_out = zeros(3,1);
    H_out = zeros(3,1);
end

Eref_o = Am(3)*E_ro;
Href_o = Am(3)*H_ro;

Eref_e = Am(4)*E_re;
Href_e = Am(4)*H_re;

Iout = dot(cross(E_out, conj(H_out)), ada);

Iout_ro = dot(cross(Eref_o, conj(Href_o)), -ada);
Iout_re = dot(cross(Eref_e, conj(Href_e)), -ada);


Iout_all = Iout + Iout_ro+Iout_re;


totalFluxRatio = Iout_all/Iin; % Should be approximately one without absorption.


%% Coordinate transformation matrices
[p1,s1] = calcPandSUnitVectors(k_inc,ada);

Oin = calcO(s1,p1,k_inc);


% o and e in same direction, so both should give same Oout
Oout   = calcO(E_ta, E_tb, k_out);

[pref_o, sref_o] = calcPandSUnitVectors(k_ref_o, ada);
Oref_o = calcO(sref_o, pref_o, k_ref_o);

% TODO:  S or k here?
[pref_e, sref_e] = calcPandSUnitVectors(k_ref_e, ada);
Oref_e = calcO(sref_e, pref_e, k_ref_e);

I_r = getIReflect;

I_t = eye(3);
Q_t = Oout*(I_t / Oin);
Qref_e = Oref_e*(I_r / Oin);
Qref_o = Oref_o*(I_r / Oin);

SD_t = S_out * transpose(k_inc);
SD_ro = S_ro * transpose(k_inc);
SD_re = S_re * transpose(k_inc);

child = buildPolarizedChild(ray, hit, normal, mediumOut, ...
    Mode="isotropic", ...
    BranchType="transmitted", ...
    k=k_out, ...
    S=S_out, ...
    P=P_t, ...
    Q=Q_t, ...
    O=Oout, ...
    LocalBasis=struct('s', E_ta, 'p', E_tb, 'basisDirection', k_out), ...
    Index=n_out, ...
    ModeE=E_out, ...
    ModeH=H_out, ...
    FluxNormal=ada, ...
    Active=~tir, ...
    PropagationProjector=SD_t, ...
    Metadata=struct( ...
    'Iin', Iin, ...
    'Iout', Iout, ...
    'IinField', IinField, ...
    'transmittedAmplitude', Am));

% Can have e and o reflected waves.
child_refo = buildPolarizedChild(ray, hit, normal, mediumIn, ...
    Mode="ordinary", ...
    BranchType="reflected", ...
    k=k_ref_o, ...
    S=S_ro, ...
    P=P_ro, ...
    Q=Qref_o, ...
    O=Oref_o, ...
    LocalBasis=struct('s', sref_o, 'p', pref_o, 'basisDirection', k_ref_o), ...
    Index=nO, ...
    ModeE=E_ro, ...
    ModeH=H_ro, ...
    FluxNormal=-ada, ...
    PropagationProjector=SD_ro, ...
    Metadata=struct( ...
    'Iin', Iin, ...
    'Iout', Iout_ro, ...
    'IinField', IinField, ...
    'reflectedAmplitude', Am(3), ...
    'epsilon', epsilon, ...
    'opticAxis', opticAxis));

child_refe = buildPolarizedChild(ray, hit, normal, mediumIn, ...
    Mode="extraordinary", ...
    BranchType="reflected", ...
    k=k_ref_e, ...
    S=S_re, ...
    P=P_re, ...
    Q=Qref_e, ...
    O=Oref_e, ...
    LocalBasis=struct('s', sref_e, 'p', pref_e, 'basisDirection', k_ref_e), ...
    Index=n_ref, ...
    ModeE=E_re, ...
    ModeH=H_re, ...
    FluxNormal=-ada, ...
    PhaseIndex=n_ref, ...
    PropagationProjector=SD_re, ...
    Metadata=struct( ...
    'Iin', Iin, ...
    'Iout', Iout_re, ...
    'IinField', IinField, ...
    'reflectedAmplitude', Am(4), ...
    'n_SE', n_ref*dot(k_ref_e,S_re), ...
    'epsilon', epsilon, ...
    'opticAxis', opticAxis));

IoutField = child.flux;
IoutField_ref_o = child_refo.flux;
IoutField_ref_e = child_refe.flux;

interaction.children = [child; child_refo; child_refe];

interaction.frames.Oin = Oin;
interaction.frames.Oout = Oout;
interaction.frames.OrefOrdinary = Oref_o;
interaction.frames.OrefExtraordinary = Oref_e;
interaction.frames.Qout = Q_t;
interaction.frames.QrefOrdinary = Qref_o;
interaction.frames.QrefExtraordinary = Qref_e;
interaction.frames.inputBasis = struct('E', E_inc, 'En', E_n, 'basisDirection', S_inc);
interaction.frames.outputBasis = child.localBasis;
interaction.frames.reflectedOrdinaryBasis = child_refo.localBasis;
interaction.frames.reflectedExtraordinaryBasis = child_refe.localBasis;

interaction.P = struct( ...
    'transmitted', P_t, ...
    'reflectedOrdinary', P_ro, ...
    'reflectedExtraordinary', P_re);
interaction.Q = struct( ...
    'transmitted', Q_t, ...
    'reflectedOrdinary', Qref_o, ...
    'reflectedExtraordinary', Qref_e);
interaction.coefficients = struct( ...
    'Am', Am, ...
    'Ap', Ap, ...
    'transmitted', Am(1:2), ...
    'reflectedOrdinary', Am(3), ...
    'reflectedExtraordinary', Am(4));
interaction.diagnostics = struct( ...
    'F', F, ...
    'Cm', Cm, ...
    'Cn', Cn, ...
    'boundaryResidual_m', F*Am - Cm, ...
    'boundaryResidual_n', F*Ap - Cn, ...
    'Iin', Iin, ...
    'Iout', Iout, ...
    'totalFluxRatio', totalFluxRatio, ...
    'IinField', IinField, ...
    'IoutField', IoutField, ...
    'IoutOrdinaryReflected', Iout_ro, ...
    'IoutExtraordinaryReflected', Iout_re, ...
    'IoutFieldOrdinaryReflected', IoutField_ref_o, ...
    'IoutFieldExtraordinaryReflected', IoutField_ref_e, ...
    'totalFluxRatioField', ...
        (IoutField + IoutField_ref_o + IoutField_ref_e)/IinField, ...
    'tir', tir, ...
    'epsilon', epsilon, ...
    'opticAxis', opticAxis, ...
    'n_ref_e', n_ref, ...
    'k_ref_e', k_ref_e, ...
    'q_ref_e', q_ref, ...
    'k_ref_o', k_ref_o, ...
    'E_ro', E_ro, ...
    'H_ro', H_ro, ...
    'E_re', E_re, ...
    'H_re', H_re);



end
