% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function outputPath = generateRemainingExampleBaselines(outputPath)
%GENERATEREMAININGEXAMPLEBASELINES Export example 3 and mirror references.

repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1
    outputPath = fullfile(repositoryRoot, 'pyprtLab', 'tests', ...
        'baselines', 'remainingExampleBaselines.json');
end
addpath(fullfile(repositoryRoot, 'prtLab'));
addpath(fullfile(repositoryRoot, 'examples'));

cellSystem = exampleCellPhoneLensEx3System();
cellOptions = prtDefaultOptions();
cellOptions.minAmplitude = 0.2;
cellOutput = polarizationRayTrace( ...
    cellSystem, [0;0;1], [0;0.4;-0.1], [0;1], cellOptions);
cellFinal = cellOutput.rays(cellOutput.finalRayIds(1));
dominantPositions = zeros(0, 3);
for rayId = cellFinal.history
    interactionIndex = find( ...
        [cellOutput.interactions.parentRayId] == rayId, 1);
    if ~isempty(interactionIndex)
        dominantPositions(end + 1, :) = ...
            cellOutput.interactions(interactionIndex).position.';
    end
end

mirrorSystem = examplePlaneMirrorSystem();
angle = 30;
mirrorOutput = polarizationRayTrace( ...
    mirrorSystem, [0;sind(angle);cosd(angle)], [0;0;0], ...
    [1;1]/sqrt(2));
mirrorInteraction = mirrorOutput.interactions(1);
reflectedIndex = find( ...
    [mirrorInteraction.children.branchType] == "reflected", 1);
reflected = mirrorInteraction.children(reflectedIndex);

fixture = struct( ...
    'schemaVersion', 1, ...
    'referenceImplementation', "MATLAB prtLab", ...
    'referenceCommit', "2682ac1deb00040ee59f48b8516a962a6b6a24ff", ...
    'generator', "tests/generateRemainingExampleBaselines.m", ...
    'absoluteTolerance', 2e-9, ...
    'cellPhoneExample3', struct( ...
        'dominantPositions', packNumeric(dominantPositions), ...
        'finalK', packNumeric(cellFinal.k), ...
        'finalFieldE', packNumeric(cellFinal.fieldE), ...
        'finalP', packNumeric(cellFinal.P), ...
        'finalFlux', packNumeric(cellFinal.flux), ...
        'finalOPL', packNumeric(cellFinal.OPL)), ...
    'planeMirror', struct( ...
        'angleDeg', angle, ...
        'reflectedK', packNumeric(reflected.k), ...
        'reflectedFieldE', packNumeric(reflected.fieldE), ...
        'reflectedFieldH', packNumeric(reflected.fieldH), ...
        'reflectedP', packNumeric(reflected.P), ...
        'reflectedFlux', packNumeric(reflected.flux), ...
        'As', packNumeric(mirrorInteraction.coefficients.As), ...
        'Ap', packNumeric(mirrorInteraction.coefficients.Ap)));

outputFolder = fileparts(outputPath);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
fileId = fopen(outputPath, 'w');
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', jsonencode(fixture, PrettyPrint=true));
fprintf('Wrote %s\n', outputPath);
end


function packed = packNumeric(value)
packed = struct('real', real(value), 'imag', imag(value));
end
