% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function outputPath = generateJonesAnalysisBaselines(outputPath)
%GENERATEJONESANALYSISBASELINES Export polarization ellipse references.

repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1
    outputPath = fullfile(repositoryRoot, 'pyprtLab', 'tests', ...
        'baselines', 'jonesAnalysisBaselines.json');
end
addpath(fullfile(repositoryRoot, 'prtLab'));

fields = [ ...
    1, 0, 1/sqrt(2), 1/sqrt(2), 1/sqrt(2), 1, 0.8*exp(-0.2i); ...
    0, 1, 1/sqrt(2), 1i/sqrt(2), -1i/sqrt(2), 0.4i, 0.3*exp(0.7i)];
[psi, ellipticity, majorAxis, major, minor] = ...
    jonesMajorAxisEllipticity(fields);

fixture = struct( ...
    'schemaVersion', 1, ...
    'referenceImplementation', "MATLAB prtLab", ...
    'referenceCommit', "2682ac1deb00040ee59f48b8516a962a6b6a24ff", ...
    'generator', "tests/generateJonesAnalysisBaselines.m", ...
    'absoluteTolerance', 5e-13, ...
    'fields', packNumeric(fields), ...
    'psi', packNumeric(psi), ...
    'ellipticity', packNumeric(ellipticity), ...
    'majorAxis', packNumeric(majorAxis), ...
    'major', packNumeric(major), ...
    'minor', packNumeric(minor));

outputFolder = fileparts(outputPath);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
fileId = fopen(outputPath, 'w');
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', jsonencode(fixture, PrettyPrint=true));
fprintf('Wrote %s\n', outputPath);
end


function packed = packNumeric(value)
packed = struct('real', real(value), 'imag', imag(value));
end
