% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function outputPath = generateCoordinateTransformBaselines(outputPath)
%GENERATECOORDINATETRANSFORMBASELINES Export P-to-Jones reference cases.

repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1
    outputPath = fullfile(repositoryRoot, 'pyprtLab', 'tests', ...
        'baselines', 'coordinateTransformBaselines.json');
end
addpath(fullfile(repositoryRoot, 'prtLab'));

P = [ ...
    0.82 + 0.11i,  0.04 - 0.03i,  0.07; ...
   -0.02 + 0.05i,  0.91 - 0.08i, -0.03; ...
    0.01 - 0.02i,  0.06 + 0.01i,  1.00];
ki = prtNorm([0.20;-0.30;0.93]);
kj = prtNorm([-0.25;0.15;0.96]);

doublePoleIn = struct( ...
    'type', "doublePole", 'a_loc', [0;0;1], 'x_o', [1;0;0]);
doublePoleOut = struct( ...
    'type', "doublePole", 'a_loc', [0;1;0], 'x_o', [1;0;0]);
dipoleIn = struct('type', "dipole", 'a_loc', [0;0;1]);
dipoleOut = struct('type', "dipole", 'a_loc', [0;1;0]);
spIn = struct('type', "sp", 'normal', prtNorm([0.1;0;1]));
spOut = struct('type', "sp", 'normal', prtNorm([0;-0.2;1]));

cases = [ ...
    makeCase("doublePole-shared", P, ki, kj, doublePoleIn, doublePoleIn); ...
    makeCase("doublePole-distinct", P, ki, kj, doublePoleIn, doublePoleOut); ...
    makeCase("dipole-shared", P, ki, kj, dipoleIn, dipoleIn); ...
    makeCase("dipole-distinct", P, ki, kj, dipoleIn, dipoleOut); ...
    makeCase("sp-distinct-normals", P, ki, kj, spIn, spOut); ...
    makeCase("dipole-pole", P, [0;0;1], kj, dipoleIn, dipoleIn)];

fixture = struct( ...
    'schemaVersion', 1, ...
    'referenceImplementation', "MATLAB prtLab", ...
    'referenceCommit', "2682ac1deb00040ee59f48b8516a962a6b6a24ff", ...
    'generator', "tests/generateCoordinateTransformBaselines.m", ...
    'absoluteTolerance', 5e-12, ...
    'cases', cases);

outputFolder = fileparts(outputPath);
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
fileId = fopen(outputPath, 'w');
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, '%s\n', jsonencode(fixture, PrettyPrint=true));
fprintf('Wrote %s\n', outputPath);
end


function result = makeCase(name, P, ki, kj, coordIn, coordOut)
[J, xOut, yOut] = transformPtoJones(P, ki, kj, coordIn, coordOut);
result = struct( ...
    'name', name, ...
    'P', packNumeric(P), ...
    'ki', packNumeric(ki), ...
    'kj', packNumeric(kj), ...
    'coordIn', serializeCoordinates(coordIn), ...
    'coordOut', serializeCoordinates(coordOut), ...
    'J', packNumeric(J), ...
    'xOut', packNumeric(xOut), ...
    'yOut', packNumeric(yOut));
end


function result = serializeCoordinates(coord)
result = struct('type', coord.type);
fields = ["a_loc", "x_o", "normal"];
for field = fields
    if isfield(coord, field)
        result.(field) = packNumeric(coord.(field));
    end
end
end


function packed = packNumeric(value)
packed = struct('real', real(value), 'imag', imag(value));
end
