% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

function T = exampleQuarterWavePlateSystem()
%EXAMPLEQUARTERWAVEPLATESYSTEM Air/calcite quarter-wave plate/air example.
%
%   This system is inspired by Chapter 20 Example 20.1. Length units are um.

lambda = 0.633; % um
nO = 1.656;
nE = 1.485;
tQwp = 1.25 * lambda / (nO - nE);
opticAxis = [-sqrt(2)/2; -sqrt(2)/2; 0];

T = createOpticalSystem(lambda);
T.Properties.UserData.lambdaUnits = 'um';

airIndex = struct('n', 1.0);
airAxis = struct();
calciteIndex = struct('nO', nO, 'nE', nE);
calciteAxis = struct('opticAxis', opticAxis);
bareCoating = struct('type', 'bare');

% Object/input space. The zero-thickness row makes the incident medium
% explicit without adding propagation.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

% Plane entrance surface followed by propagation through the calcite plate.
T = addSurface( ...
    T, ...
    Inf, ...
    tQwp, ...
    "plane", ...
    struct(), ...
    "uniaxial", ...
    calciteIndex, ...
    calciteAxis, ...
    bareCoating);

% Plane exit surface into air. Thickness is zero because this row describes
% the output medium after the waveplate.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

end
