function T = exampleAchromaticWavePlateSystem()
%exampleAchromaticWavePlateSystem  quarter-wave plate/air example.
%
%   This system is inspired by Chapter 20 Example 20.1. Length units are um.

lambda = 0.633; % um
[nO1, nE1] = quartzOpticalConstants(lambda);
[nO2, nE2] = mgF2OpticalConstants(lambda);
t1 = 230.537086;
tgap = 444.5;
t2 = 190.217463;
opticAxis_1 = [-sqrt(2)/2; -sqrt(2)/2; 0];
opticAxis_2 = [sqrt(2)/2; -sqrt(2)/2; 0];


T = createOpticalSystem(lambda);
T.Properties.UserData.lambdaUnits = 'um';

airIndex = struct('n', 1.0);
airAxis = struct();
quartzIndex = struct('nO', nO1, 'nE', nE1);
quartzAxis = struct('opticAxis', opticAxis_1);
bareCoating = struct('type', 'bare');

mgF2Index = struct('nO', nO2, 'nE', nE2);
mgF2Axis = struct('opticAxis', opticAxis_2);

% Object/input space. The zero-thickness row makes the incident medium
% explicit without adding propagation.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

% Plane entrance surface followed by propagation through the calcite plate.
T = addSurface( ...
    T, ...
    Inf, ...
    t1, ...
    "plane", ...
    struct(), ...
    "uniaxial", ...
    quartzIndex, ...
    quartzAxis, ...
    bareCoating);

T = addSurface( ...
    T, ...
    Inf, ...
    tgap, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

% Second surface as other material/orientation.  
T = addSurface( ...
    T, ...
    Inf, ...
    t2, ...
    "plane", ...
    struct(), ...
    "uniaxial", ...
    mgF2Index, ...
    mgF2Axis, ...
    bareCoating);

% Plane exit surface into air. Thickness is zero because this row describes
% the output medium after the waveplate.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

end
