function T = exampleCassegrainTelescope()
%
%
lambda = 0.500e-3; % mm
T = createOpticalSystem(lambda);
T.Properties.UserData.lambdaUnits = 'mm';
T.Properties.UserData.description = 'Cassegrain Telescope';

radius = [ ...
    -5688.0, -1228.28];

nMirror = 0.958 + 6.69*1i;
nAfter = [nMirror, nMirror];

asphereData = [ ...
   (-1.0+1.0), 0, 0, 0, 0, 0, 0, 0, 0; ...
   (-1.78+1.0), 0, 0, 0, 0, 0, 0, 0, 0];

thicknessAfter = [ ...
    -2317.80, 3674.784];
thicknessToSurface = [0, thicknessAfter(1:end-1)];

asphereLabels = {'kappa','A3','A4','A5','A6','A7','A8','A9','A10'};
coatingData = struct('type', 'bare');
axisData = struct();

nBefore = [1.0, nAfter(1:end-1)];
for surfaceIndex = 1:numel(radius)
    if isinf(radius(surfaceIndex))
        surfaceType = "plane";
    else
        surfaceType = "odd_asphere";
    end

    surfaceData = struct( ...
        'kappa', asphereData(surfaceIndex, 1), ...
        'A', asphereData(surfaceIndex, 2:end), ...
        'labels', {asphereLabels}, ...
        'clearAperture', 1.0, ...
        'isReflective', true);

    T = addSurface( ...
        T, ...
        radius(surfaceIndex), ...
        thicknessToSurface(surfaceIndex), ...
        surfaceType, ...
        surfaceData, ...
        "isotropic", ...
        struct('n', nBefore(surfaceIndex)), ...
        axisData, ...
        coatingData);
end

imageSurfaceData = struct( ...
    'note', 'image plane');
T = addSurface( ...
    T, ...
    Inf, ...
    thicknessAfter(end), ...
    "plane", ...
    imageSurfaceData, ...
    "isotropic", ...
    struct('n', nMirror), ...
    axisData, ...
    coatingData);

outputMediumData = struct( ...
    'note', 'output medium after image plane');
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "medium", ...
    outputMediumData, ...
    "isotropic", ...
    struct('n', 1.0), ...
    axisData, ...
    coatingData);

end
