function T = examplePlaneMirrorSystem()
%EXAMPLEPLANEMIRRORSYSTEM Minimal air-to-metal plane mirror test system.

lambda = 0.500e-3; % mm
T = createOpticalSystem(lambda);
T.Properties.UserData.lambdaUnits = 'mm';
T.Properties.UserData.description = 'Plane mirror';

air = struct('n', 1.0);
aluminum = struct('n', 0.958 + 6.69i);
axisData = struct();
coatingData = struct('type', 'bare');

mirrorSurfaceData = struct( ...
    'note', 'plane mirror', ...
    'clearAperture', 1.0);
T = addSurface( ...
    T, ...
    Inf, ...
    0.0, ...
    "plane", ...
    mirrorSurfaceData, ...
    "isotropic", ...
    air, ...
    axisData, ...
    coatingData);

metalSideData = struct( ...
    'note', 'complex-index metal side', ...
    'clearAperture', 1.0);
T = addSurface( ...
    T, ...
    Inf, ...
    0.0, ...
    "plane", ...
    metalSideData, ...
    "isotropic", ...
    aluminum, ...
    axisData, ...
    coatingData);

end
