%EXAMPLETWOPRISMSCENE Trace through two isotropic prisms and their air gap.
addpath(genpath('..'));

lambda = 0.633; % um
scene = createGlanTaylorPolarizerScene(struct('n', 1.2), ...
    LegY=10, ...
    LegZ=10, ...
    Width=8, ...
    AirGap=0.2, ...
    lambda=lambda, ...
    lambdaUnits="um", ...
    Name="Two-prism scene test");

kIn = [0;0;1];
xIn = [0;5;-1];
Ein = [1;0];
options = prtDefaultOptions();
options.maxInteractions = 8;
options.minAmplitude = 1e-8;

rayOutput = polarizationRayTraceScene(scene, kIn, xIn, Ein, options);

disp("Hit sequence:");
for ii = 1:numel(rayOutput.interactions)
    data = rayOutput.interactions(ii).interceptData;
    fprintf("  %s / %s (%s)\n", ...
        data.solidName, data.faceName, data.direction);
end

figure;
plotPrtSystem3D(scene, rayOutput, ...
    PreExtend=1, ...
    PostExtend=1, ...
    ShowPolarization=false, ...
    AxisPaddingFraction=0.2);
title(scene.name);
