% Copyright (c) 2026 Jeremy Nesbitt. All rights reserved.
% Use of this source code is governed by a BSD-style license that can be
% found in the LICENSE file.

%EXAMPLERIGHTTRIANGULARCRYSTALPRISM Build and display a crystal prism.

lambda = 0.633; % um
calcite = struct('nO', 1.6557, 'nE', 1.4852);

prism = createRightTriangularPrismSolid(calcite, ...
    LegY=12, ...
    LegZ=12, ...
    Width=8, ...
    OpticAxis=[1;0;0], ...
    lambda=lambda, ...
    lambdaUnits="um", ...
    Name="Calcite right triangular prism");

figure;
plotPrtSystem3D(prism, [], ShowRays=false, ShowPolarization=false);
title(prism.name);
