function T = modAchromaticWavePlateSystem(lambda, nO1, nE1, nO2, nE2, t1, tgap, t2, opticAxis_1, opticAxis_2)
%modOpticallyContactedWavePlateSystem modular optically contacted
%waveplate created for characterization vs wavelength.


T = createOpticalSystem(lambda);
T.Properties.UserData.lambdaUnits = 'um';

airIndex = struct('n', 1.0);
airAxis = struct();
quartzIndex = struct('nO', nO1, 'nE', nE1);
quartzAxis = struct('opticAxis', opticAxis_1);
bareCoating = struct('type', 'bare');

mgF2Index = struct('nO', nO2, 'nE', nE2);
mgF2Axis = struct('opticAxis', opticAxis_2);

% Object/input space. The zero-thickness row makes the incident medium
% explicit without adding propagation.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

% Plane entrance surface followed by propagation through the calcite plate.
T = addSurface( ...
    T, ...
    Inf, ...
    t1, ...
    "plane", ...
    struct(), ...
    "uniaxial", ...
    quartzIndex, ...
    quartzAxis, ...
    bareCoating);

T = addSurface( ...
    T, ...
    Inf, ...
    tgap, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

% Second surface as other material/orientation.  
T = addSurface( ...
    T, ...
    Inf, ...
    t2, ...
    "plane", ...
    struct(), ...
    "uniaxial", ...
    mgF2Index, ...
    mgF2Axis, ...
    bareCoating);

% Plane exit surface into air. Thickness is zero because this row describes
% the output medium after the waveplate.
T = addSurface( ...
    T, ...
    Inf, ...
    0, ...
    "plane", ...
    struct(), ...
    "isotropic", ...
    airIndex, ...
    airAxis, ...
    bareCoating);

end
