#!/usr/bin/env python3
"""Convert the documentation notebooks to GitHub-compatible Markdown."""

from __future__ import annotations

import base64
import json
import re
import shutil
from pathlib import Path
from typing import Any


DOCS_DIR = Path(__file__).resolve().parent
ASSETS_DIR = DOCS_DIR / "assets"
ANSI_ESCAPE = re.compile(r"\x1b\[[0-?]*[ -/]*[@-~]")


def as_text(value: Any) -> str:
    if isinstance(value, list):
        return "".join(str(part) for part in value)
    return str(value)


def write_binary_asset(path: Path, encoded_data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = "".join(encoded_data) if isinstance(encoded_data, list) else encoded_data
    path.write_bytes(base64.b64decode(payload))


def write_text_asset(path: Path, text: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(as_text(text), encoding="utf-8")


def extract_attachments(cell: dict[str, Any], asset_dir: Path, relative_dir: Path) -> str:
    source = as_text(cell.get("source", ""))
    for name, representations in cell.get("attachments", {}).items():
        safe_name = Path(name).name
        if "image/png" in representations:
            write_binary_asset(asset_dir / safe_name, representations["image/png"])
        elif "image/jpeg" in representations:
            write_binary_asset(asset_dir / safe_name, representations["image/jpeg"])
        elif "image/svg+xml" in representations:
            write_text_asset(asset_dir / safe_name, representations["image/svg+xml"])
        else:
            continue
        source = source.replace(
            f"attachment:{name}", (relative_dir / safe_name).as_posix()
        )
    return source


def fenced_block(text: str, language: str = "text") -> str:
    text = "\n".join(line.rstrip() for line in text.splitlines())
    fence = "```"
    while fence in text:
        fence += "`"
    return f"{fence}{language}\n{text.rstrip()}\n{fence}\n"


def render_output(
    output: dict[str, Any],
    cell_index: int,
    output_index: int,
    asset_dir: Path,
    relative_dir: Path,
) -> list[str]:
    output_type = output.get("output_type", "")
    if output_type == "stream":
        text = as_text(output.get("text", ""))
        return [fenced_block(text)] if text.strip() else []

    if output_type == "error":
        traceback = "\n".join(output.get("traceback", []))
        traceback = ANSI_ESCAPE.sub("", traceback)
        return [fenced_block(traceback)] if traceback.strip() else []

    data = output.get("data", {})
    stem = f"cell_{cell_index:03d}_output_{output_index:02d}"
    rendered: list[str] = []

    image_types = (
        ("image/png", ".png", write_binary_asset),
        ("image/jpeg", ".jpg", write_binary_asset),
        ("image/svg+xml", ".svg", write_text_asset),
    )
    for mime_type, extension, writer in image_types:
        if mime_type in data:
            filename = stem + extension
            writer(asset_dir / filename, data[mime_type])
            rendered.append(f"![Notebook output]({(relative_dir / filename).as_posix()})\n")
            return rendered

    if "text/markdown" in data:
        rendered.append(as_text(data["text/markdown"]).rstrip() + "\n")
    elif "text/html" in data:
        rendered.append(as_text(data["text/html"]).rstrip() + "\n")
    elif "text/plain" in data:
        text = as_text(data["text/plain"])
        if text.strip():
            rendered.append(fenced_block(text))
    return rendered


def convert_notebook(notebook_path: Path) -> Path:
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    notebook_name = notebook_path.stem
    asset_dir = ASSETS_DIR / notebook_name
    shutil.rmtree(asset_dir, ignore_errors=True)
    relative_asset_dir = Path("assets") / notebook_name
    language = (
        notebook.get("metadata", {})
        .get("kernelspec", {})
        .get("language", "")
        .lower()
    )
    code_language = "matlab" if language == "matlab" else language

    sections = [
        "<!-- Generated from "
        + notebook_path.relative_to(DOCS_DIR).as_posix()
        + "; do not edit this file directly. -->\n"
    ]

    for cell_index, cell in enumerate(notebook.get("cells", []), start=1):
        cell_type = cell.get("cell_type")
        if cell_type == "markdown":
            text = extract_attachments(cell, asset_dir, relative_asset_dir)
            if text.strip():
                sections.append(text.rstrip() + "\n")
        elif cell_type == "code":
            source = as_text(cell.get("source", ""))
            if source.strip():
                sections.append(fenced_block(source, code_language))
            for output_index, output in enumerate(cell.get("outputs", []), start=1):
                sections.extend(
                    render_output(
                        output,
                        cell_index,
                        output_index,
                        asset_dir,
                        relative_asset_dir,
                    )
                )

    output_path = DOCS_DIR / f"{notebook_name}.md"
    output_path.write_text("\n".join(sections).rstrip() + "\n", encoding="utf-8")
    return output_path


def main() -> None:
    notebooks = sorted(DOCS_DIR.rglob("*.ipynb"))
    if not notebooks:
        raise SystemExit(f"No notebooks found below {DOCS_DIR}")

    notebooks_by_name: dict[str, Path] = {}
    for notebook in notebooks:
        previous = notebooks_by_name.get(notebook.stem)
        if previous is not None:
            raise SystemExit(
                "Notebook names must be unique when Markdown is written to "
                f"{DOCS_DIR}: {previous} and {notebook}"
            )
        notebooks_by_name[notebook.stem] = notebook

    if ASSETS_DIR.exists():
        expected_asset_dirs = set(notebooks_by_name)
        for path in ASSETS_DIR.iterdir():
            if path.is_file() or path.is_symlink():
                path.unlink()
            elif path.name not in expected_asset_dirs:
                shutil.rmtree(path)

    for notebook in notebooks:
        output = convert_notebook(notebook)
        print(f"Generated {output.relative_to(DOCS_DIR.parent)}")


if __name__ == "__main__":
    main()
